@ Battle Tower
gText_AnabelWonSilver::
	.string "It's very disappointing…$"

gText_AnabelDefeatSilver::
	.string "Okay, I understand…$"

gText_AnabelWonGold::
	.string "I'm terribly sorry…$"

gText_AnabelDefeatGold::
	.string "Thank you…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "Ahahaha! Aren't you embarrassed?\n"
	.string "Everyone's watching!$"

gText_TuckerDefeatSilver::
	.string "Grr…\n"
	.string "What the…$"

gText_TuckerWonGold::
	.string "My Dome Ace title isn't just for show!$"

gText_TuckerDefeatGold::
	.string "Ahahaha!\n"
	.string "You're inspiring!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "Way to work!\n"
	.string "That was a good lesson, eh?$"

gText_NolandDefeatSilver::
	.string "Good job!\n"
	.string "You know what you're doing!$"

gText_NolandWonGold::
	.string "Hey, hey, hey!\n"
	.string "You're finished already?$"

gText_NolandDefeatGold::
	.string "What happened here?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Humph…$"

gText_LucyDefeatSilver::
	.string "Urk…$"

gText_LucyWonGold::
	.string "Hah!$"

gText_LucyDefeatGold::
	.string "Darn!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "Oh, come on!\n"
	.string "You have to try harder than that!$"

gText_GretaDefeatSilver::
	.string "No way!\n"
	.string "Good job!$"

gText_GretaWonGold::
	.string "Heheh!\n"
	.string "What did you expect?$"

gText_GretaDefeatGold::
	.string "Huh?\n"
	.string "Are you serious?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Your Pokémon are wimpy because\n"
	.string "you're wimpy as a Trainer!$"

gText_SpenserDefeatSilver::
	.string "Ah…\n"
	.string "Now this is something else…$"

gText_SpenserWonGold::
	.string "Gwahahaha!\n"
	.string "My brethren, we have nothing to fear!$"

gText_SpenserDefeatGold::
	.string "Gwah!\n"
	.string "Hahahaha!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "Hey! What's wrong with you!\n"
	.string "Let's see some effort! Get up!$"

gText_BrandonDefeatSilver::
	.string "That's it! You've done great!\n"
	.string "You've worked hard for this!$"

gText_BrandonWonGold::
	.string "Hey! Don't you give up now!\n"
	.string "Get up! Don't lose faith in yourself!$"

gText_BrandonDefeatGold::
	.string "That's it! You've done it!\n"
	.string "You kept working for this!$"

@Gym Leaders
gText_BrockIntro::
	.string "I'm Brock!\nI'm an expert on Rock-type Pokémon.\pMy defense is rock hard!$"

gText_BrockWon::
	.string "The best offense is a good defense!\n"
	.string "That's my way of doing things!$"

gText_BrockDefeat::
	.string "Your Pokémon's powerful\n"
	.string "attacks overcame my\l"
	.string "rock-hard resistance…\p"
	.string "You're stronger than\n"
	.string "I expected…$"

gText_MistyIntro::
	.string "I'm Misty!\nI'm a user of Water-type Pokémon!\lAre you good enough to beat me?"

gText_MistyWon::
	.string "See! This is the Water-type\ntoughness I was talking about!$"

gText_MistyDefeat::
	.string "You really are good…\pI'll admit that you are skilled…$"

gText_SurgeIntro::
	.string "The name's Lt. Surge!\pWhen it comes to Electric-type Pokémon,\nI'm number one!\pI'm gonna zap your Pokémon!$"

gText_SurgeWon::
	.string "Oh yeah!\nI'm strong!$"

gText_SurgeDefeat::
	.string "Arrrgh!\nYou are strong.$"

gText_ErikaIntro::
	.string "My name is Erika,\nand I love Grass-type Pokémon.\pSo, you're the one who wishes to\nchallenge me.$"

gText_ErikaWon::
	.string "I was afraid I would doze off…$"

gText_ErikaDefeat::
	.string "Oh my!\nLooks like I underestimated you…$"

gText_JanineIntro::
	.string "I'm Janine!\nI'm a modern ninja!\pFeel the horror of the Poison-type\nPokémon I use!$"

gText_JanineWon::
	.string " I'm Janine!\nRemember this name!$"

gText_JanineDefeat::
	.string "You've got a great battle technique!$"

gText_SabrinaIntro::
	.string "Three years ago I had a vision of\nbattling you.\pI am a psychic after all…\nYou still want to battle?$"

gText_SabrinaWon::
	.string "Just as I foresaw…$"

gText_SabrinaDefeat::
	.string "Was the future I saw…wrong?$"

gText_BlaineIntro::
	.string " Whoa hey!\pMy fiery Pokémon will\nincinerate all challengers!$"

gText_BlaineWon::
	.string "Whoa hey!\nI'm a raging inferno!$"

gText_BlaineDefeat::
	.string "How could this be?!\nMy spirit has not been defeated!$"

gText_GiovanniIntro::
	.string "For your insolence, you will feel a\nworld of pain!$"

gText_GiovanniWon::
	.string "Ha!\nThat was a truly intense fight!$"

gText_GiovanniDefeat::
	.string "What?\nMe, lose?!$"


gText_FalknerIntro::
	.string "I'll show you the real power of the\nmagnificent bird Pokémon!\lWinds, stay with me!$"

gText_FalknerWon::
	.string "Now you know the real power\nof bird Pokémon!$"

gText_FalknerDefeat::
	.string "I understand...\nI'll bow out gracefully.$"

gText_BugsyIntro::
	.string "I never lose when it comes to\nBug-type Pokémon.\pMy research is going to make me\nthe authority on Bug-type Pokémon!"

gText_BugsyWon::
	.string "I guess I'm done reporting\nmy research findings!$"

gText_BugsyDefeat::
	.string "Aw, that's the end of it…$"

gText_WhitneyIntro::
	.string "I'm warning you--I'm good!\pIf you lose to me,\nyou'd better not cry!"

gText_WhitneyWon::
	.string "See? Didn't I tell ya?\nMy Pokémon are really strong!$"

gText_WhitneyDefeat::
	.string "Ugh…$"

gText_MortyIntro::
	.string "Fighting against stronger foes\nis also my training!\pYou're going to help me reach the\nnext level in my training.$"

gText_MortyWon::
	.string "I moved…one step ahead again.$"

gText_MortyDefeat::
	.string "How is this possible…$"

gText_ChuckIntro::
	.string "It's a bit sudden, but we shall\ndo battle!$"

gText_ChuckWon::
	.string "See? My Pokémon were as strong\nas I said!$"

gText_ChuckDefeat::
	.string "No… Not…yet…$"

gText_JasmineIntro::
	.string "I am Jasmine.\pI use the… Clang!\nSteel type!\p…Do you know about the Steel type?$"

gText_JasmineWon::
	.string "I'm glad…\nI won…$"

gText_JasmineDefeat::
	.string "Well done…$"

gText_PryceIntro::
	.string "I, too, have seen and suffered much in\nmy life.\pSince I am your elder, let me show you\nwhat I mean.$"

gText_PryceWon::
	.string "This is winter's harshness.$"

gText_PryceDefeat::
	.string "Hmm.\nSeems as if my luck has run out.$"

gText_ClairIntro::
	.string " I am Clair.\nThe world's best Dragon-type master.\pI can hold my own against even the\nPokémon League's Elite Four.$"

gText_ClairWon::
	.string "Come on!\nYou've got to get tougher than this!$"

gText_ClairDefeat::
	.string "It's over…$"


gText_RoxanneIntro::
	.string "By battling many Trainers, you should\nlearn many things.$"

gText_RoxanneWon::
	.string "I learned many things\nfrom our battle.$"

gText_RoxanneDefeat::
	.string "So…\nI lost…$"

gText_BrawlyIntro::
	.string "Pokémon battles are similar to how\nwaves come in and out!\pI'm going to see if you're the kind\nof Trainer who can read that motion!$"

gText_BrawlyWon::
	.string "All right!\nI rode the big wave!$"

gText_BrawlyDefeat::
	.string "Whoa, wow! You made a much bigger\nsplash than I expected!$"

gText_WattsonIntro::
	.string "You look like you have a lot of zip!\nThat's a good thing. Wahahahaha!\pThen I, Wattson, shall electrify you\nwith my Pokémon!$"

gText_WattsonWon::
	.string "Wahahahah! Well, I won!\nHow was the battle? Thrilling, right?$"

gText_WattsonDefeat::
	.string "Wahahahah! Fine, I lost!\nYou ended up giving me a thrill!$"

gText_FlanneryIntro::
	.string "With skills inherited from my\ngrandfather, who was once one of the\l Elite Four, I'm going to demonstrate\l the hot moves I honed close to a\l volcano!$"

gText_FlanneryWon::
	.string " I… I won!\nI guess my well-honed moves worked!$"

gText_FlanneryDefeat::
	.string "Oh…\nI guess I was trying too hard…$"

gText_NormanIntro::
	.string "I will do everything in my power as\na Trainer to win.\pYou'd better give it your best shot, too!$"

gText_NormanWon::
	.string "We both gave everything we had.\nThat was a wonderful match.$"

gText_NormanDefeat::
	.string "…\nI… I can't…\pI can't believe it.\nI lost to you?$"

gText_WinonaIntro::
	.string "However grueling the battle, we have\ntriumphed with grace…\pWitness the elegant choreography\nof my Pokémon and I!$"

gText_WinonaWon::
	.string "Our elegant dance is finished!$"

gText_WinonaDefeat::
	.string "A Trainer that commands Pokémon\nwith more grace than I…$"

gText_TateIntro::
	.string "Thanks to my strict training,\nI can make myself one with Pokémon!\lCan you beat this combination?$"

gText_TateWon::
	.string "The combination of me and my Pokémon\nwas superior!$"

gText_TateDefeat::
	.string "The… The combination of\nme and my Pokémon!$"

gText_LizaIntro::
	.string "Thanks to my strict training,\nI can make myself one with Pokémon!\lCan you beat this combination?$"

gText_LizaWon::
	.string "The combination of me and my Pokémon\nwas superior!$"

gText_LizaDefeat::
	.string "Oh! The combination of me and my Pokémon…$"

gText_WallaceIntro::
	.string "You have overcome challenges and\nmade it this far because you\lworked as one with your Pokémon.\lShow me that strength here and now!$"

gText_WallaceWon::
	.string "I've shown you plenty of the\nwater illusions performed\lby me and my Pokémon!$"

gText_WallaceDefeat::
	.string "That was wonderful work.\pYou were elegant--infuriatingly so!\pAnd you know, it was utterly glorious!$"
