@ Battle Tower
gText_AnabelWonSilver::
	.string "It's very disappointing…$"

gText_AnabelDefeatSilver::
	.string "Okay, I understand…$"

gText_AnabelWonGold::
	.string "I'm terribly sorry…$"

gText_AnabelDefeatGold::
	.string "Thank you…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "Ahahaha! Aren't you embarrassed?\n"
	.string "Everyone's watching!$"

gText_TuckerDefeatSilver::
	.string "Grr…\n"
	.string "What the…$"

gText_TuckerWonGold::
	.string "My Dome Ace title isn't just for show!$"

gText_TuckerDefeatGold::
	.string "Ahahaha!\n"
	.string "You're inspiring!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "Way to work!\n"
	.string "That was a good lesson, eh?$"

gText_NolandDefeatSilver::
	.string "Good job!\n"
	.string "You know what you're doing!$"

gText_NolandWonGold::
	.string "Hey, hey, hey!\n"
	.string "You're finished already?$"

gText_NolandDefeatGold::
	.string "What happened here?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Humph…$"

gText_LucyDefeatSilver::
	.string "Urk…$"

gText_LucyWonGold::
	.string "Hah!$"

gText_LucyDefeatGold::
	.string "Darn!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "Oh, come on!\n"
	.string "You have to try harder than that!$"

gText_GretaDefeatSilver::
	.string "No way!\n"
	.string "Good job!$"

gText_GretaWonGold::
	.string "Heheh!\n"
	.string "What did you expect?$"

gText_GretaDefeatGold::
	.string "Huh?\n"
	.string "Are you serious?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Your Pokémon are wimpy because\n"
	.string "you're wimpy as a Trainer!$"

gText_SpenserDefeatSilver::
	.string "Ah…\n"
	.string "Now this is something else…$"

gText_SpenserWonGold::
	.string "Gwahahaha!\n"
	.string "My brethren, we have nothing to fear!$"

gText_SpenserDefeatGold::
	.string "Gwah!\n"
	.string "Hahahaha!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "Hey! What's wrong with you!\n"
	.string "Let's see some effort! Get up!$"

gText_BrandonDefeatSilver::
	.string "That's it! You've done great!\n"
	.string "You've worked hard for this!$"

gText_BrandonWonGold::
	.string "Hey! Don't you give up now!\n"
	.string "Get up! Don't lose faith in yourself!$"

gText_BrandonDefeatGold::
	.string "That's it! You've done it!\n"
	.string "You kept working for this!$"

@Gym Leaders
gText_BrockIntro::
	.string "I'm Brock!\nI'm an expert on Rock-type Pokémon.\pMy defense is rock hard!$"

gText_BrockWon::
	.string "The best offense is a good defense!\n"
	.string "That's my way of doing things!$"

gText_BrockDefeat::
	.string "Your Pokémon's powerful\n"
	.string "attacks overcame my\l"
	.string "rock-hard resistance…\p"
	.string "You're stronger than\n"
	.string "I expected…$"

gText_MistyIntro::
	.string "I'm Misty!\nI'm a user of Water-type Pokémon!\lAre you good enough to beat me?$"

gText_MistyWon::
	.string "See! This is the Water-type\ntoughness I was talking about!$"

gText_MistyDefeat::
	.string "You really are good…\pI'll admit that you are skilled…$"

gText_SurgeIntro::
	.string "The name's Lt. Surge!\pWhen it comes to Electric-type Pokémon,\nI'm number one!\pI'm gonna zap your Pokémon!$"

gText_SurgeWon::
	.string "Oh yeah!\nI'm strong!$"

gText_SurgeDefeat::
	.string "Arrrgh!\nYou are strong.$"

gText_ErikaIntro::
	.string "My name is Erika,\nand I love Grass-type Pokémon.\pSo, you're the one who wishes to\nchallenge me.$"

gText_ErikaWon::
	.string "I was afraid I would doze off…$"

gText_ErikaDefeat::
	.string "Oh my!\nLooks like I underestimated you…$"

gText_JanineIntro::
	.string "I'm Janine!\nI'm a modern ninja!\pFeel the horror of the Poison-type\nPokémon I use!$"

gText_JanineWon::
	.string " I'm Janine!\nRemember this name!$"

gText_JanineDefeat::
	.string "You've got a great battle technique!$"

gText_SabrinaIntro::
	.string "Three years ago I had a vision of\nbattling you.\pI am a psychic after all…\nYou still want to battle?$"

gText_SabrinaWon::
	.string "Just as I foresaw…$"

gText_SabrinaDefeat::
	.string "Was the future I saw…wrong?$"

gText_BlaineIntro::
	.string " Whoa hey!\pMy fiery Pokémon will\nincinerate all challengers!$"

gText_BlaineWon::
	.string "Whoa hey!\nI'm a raging inferno!$"

gText_BlaineDefeat::
	.string "How could this be?!\nMy spirit has not been defeated!$"

gText_GiovanniIntro::
	.string "For your insolence, you will feel a\nworld of pain!$"

gText_GiovanniWon::
	.string "Ha!\nThat was a truly intense fight!$"

gText_GiovanniDefeat::
	.string "What?\nMe, lose?!$"


gText_FalknerIntro::
	.string "I'll show you the real power of the\nmagnificent bird Pokémon!\lWinds, stay with me!$"

gText_FalknerWon::
	.string "Now you know the real power\nof bird Pokémon!$"

gText_FalknerDefeat::
	.string "I understand...\nI'll bow out gracefully.$"

gText_BugsyIntro::
	.string "I never lose when it comes to\nBug-type Pokémon.\pMy research is going to make me\nthe authority on Bug-type Pokémon!$"

gText_BugsyWon::
	.string "I guess I'm done reporting\nmy research findings!$"

gText_BugsyDefeat::
	.string "Aw, that's the end of it…$"

gText_WhitneyIntro::
	.string "I'm warning you--I'm good!\pIf you lose to me,\nyou'd better not cry!$"

gText_WhitneyWon::
	.string "See? Didn't I tell ya?\nMy Pokémon are really strong!$"

gText_WhitneyDefeat::
	.string "Ugh…$"

gText_MortyIntro::
	.string "Fighting against stronger foes\nis also my training!\pYou're going to help me reach the\nnext level in my training.$"

gText_MortyWon::
	.string "I moved…one step ahead again.$"

gText_MortyDefeat::
	.string "How is this possible…$"

gText_ChuckIntro::
	.string "It's a bit sudden, but we shall\ndo battle!$"

gText_ChuckWon::
	.string "See? My Pokémon were as strong\nas I said!$"

gText_ChuckDefeat::
	.string "No… Not…yet…$"

gText_JasmineIntro::
	.string "I am Jasmine.\pI use the… Clang!\nSteel type!\p…Do you know about the Steel type?$"

gText_JasmineWon::
	.string "I'm glad…\nI won…$"

gText_JasmineDefeat::
	.string "Well done…$"

gText_PryceIntro::
	.string "I, too, have seen and suffered much in\nmy life.\pSince I am your elder, let me show you\nwhat I mean.$"

gText_PryceWon::
	.string "This is winter's harshness.$"

gText_PryceDefeat::
	.string "Hmm.\nSeems as if my luck has run out.$"

gText_ClairIntro::
	.string " I am Clair.\nThe world's best Dragon-type master.\pI can hold my own against even the\nPokémon League's Elite Four.$"

gText_ClairWon::
	.string "Come on!\nYou've got to get tougher than this!$"

gText_ClairDefeat::
	.string "It's over…$"


gText_RoxanneIntro::
	.string "By battling many Trainers, you should\nlearn many things.$"

gText_RoxanneWon::
	.string "I learned many things\nfrom our battle.$"

gText_RoxanneDefeat::
	.string "So…\nI lost…$"

gText_BrawlyIntro::
	.string "Pokémon battles are similar to how\nwaves come in and out!\pI'm going to see if you're the kind\nof Trainer who can read that motion!$"

gText_BrawlyWon::
	.string "All right!\nI rode the big wave!$"

gText_BrawlyDefeat::
	.string "Whoa, wow! You made a much bigger\nsplash than I expected!$"

gText_WattsonIntro::
	.string "You look like you have a lot of zip!\nThat's a good thing. Wahahahaha!\pThen I, Wattson, shall electrify you\nwith my Pokémon!$"

gText_WattsonWon::
	.string "Wahahahah! Well, I won!\nHow was the battle? Thrilling, right?$"

gText_WattsonDefeat::
	.string "Wahahahah! Fine, I lost!\nYou ended up giving me a thrill!$"

gText_FlanneryIntro::
	.string "With skills inherited from my\ngrandfather, who was once one of the\l Elite Four, I'm going to demonstrate\l the hot moves I honed close to a\l volcano!$"

gText_FlanneryWon::
	.string " I… I won!\nI guess my well-honed moves worked!$"

gText_FlanneryDefeat::
	.string "Oh…\nI guess I was trying too hard…$"

gText_NormanIntro::
	.string "I will do everything in my power as\na Trainer to win.\pYou'd better give it your best shot, too!$"

gText_NormanWon::
	.string "We both gave everything we had.\nThat was a wonderful match.$"

gText_NormanDefeat::
	.string "…\nI… I can't…\pI can't believe it.\nI lost to you?$"

gText_WinonaIntro::
	.string "However grueling the battle, we have\ntriumphed with grace…\pWitness the elegant choreography\nof my Pokémon and I!$"

gText_WinonaWon::
	.string "Our elegant dance is finished!$"

gText_WinonaDefeat::
	.string "A Trainer that commands Pokémon\nwith more grace than I…$"

gText_TateIntro::
	.string "Thanks to my strict training,\nI can make myself one with Pokémon!\lCan you beat this combination?$"

gText_TateWon::
	.string "The combination of me and my Pokémon\nwas superior!$"

gText_TateDefeat::
	.string "The… The combination of\nme and my Pokémon!$"

gText_LizaIntro::
	.string "Thanks to my strict training,\nI can make myself one with Pokémon!\lCan you beat this combination?$"

gText_LizaWon::
	.string "The combination of me and my Pokémon\nwas superior!$"

gText_LizaDefeat::
	.string "Oh! The combination of me and my\nPokémon…$"

gText_WallaceIntro::
	.string "You have overcome challenges and\nmade it this far because you\lworked as one with your Pokémon.\lShow me that strength here and now!$"

gText_WallaceWon::
	.string "I've shown you plenty of the\nwater illusions performed\lby me and my Pokémon!$"

gText_WallaceDefeat::
	.string "That was wonderful work.\pYou were elegant--infuriatingly so!\pAnd you know, it was utterly glorious!$"

gText_RoarkIntro::
	.string "Every day, I toughened up my Pokémon\nby digging up Fossils nonstop.\pCould I show you how tough I made them\nin a battle?$"

gText_RoarkWon::
	.string "See? These are my rocking\nPokémon, my pride and joy!$"

gText_RoarkDefeat::
	.string "Wh-what? That can't be!\nMy buffed-up Pokémon!$"

gText_GardeniaIntro::
	.string "My Grass-type Pokémon are\ngrowing good and strong.\pCome on, let's battle!\nA real quick one, Ok?$"

gText_GardeniaWon::
	.string "Yes! My Pokémon and I are\nperfectly good!$"

gText_GardeniaDefeat::
	.string "Aww, really?\pMy Grass-type Pokémon are growing good\nand strong, too…$"

gText_MayleneIntro::
	.string "I'm pleased to meet you.\pI don't really know what it means to\nbe strong.\pBut I will do the best I can as\na Trainer.\pI take battling very seriously.\nWhenever you're ready!$"

gText_MayleneWon::
	.string "Thank you very much.\nI learned a lot from it.$"

gText_MayleneDefeat::
	.string "I shall admit defeat…\nYou are much too strong.$"

gText_WakeIntro::
	.string "I'm Crasher Wake!\pMy Pokémon were toughened up by\nstormy white waters!\pThey'll take everything you can throw\nat them and then pull you under!\pVictory will be ours!\nCome on, let's get it done!$"

gText_WakeWon::
	.string "I won, but I want more!\nI wanted to battle a lot more.$"

gText_WakeDefeat::
	.string "Hunwah!\nIt's gone and ended!\pHow will I say this… I want more!\nI wanted to battle a lot more!$"

gText_FantinaIntro::
	.string "I also study Pokémon very much.\nI have come to be Gym Leader.\pAnd, uh, so it shall be that you\nchallenge me.\lBut I shall win.\pThat is what the Gym Leader of\nHearthome does, non?$"

gText_FantinaWon::
	.string "You are strong.\nBut it's me who won.$"

gText_FantinaDefeat::
	.string "You are so fantastically strong.\nI know why I have lost.$"

gText_ByronIntro::
	.string "Young Trainer!\nI'm Byron.\pAs a wall for young people,\nI'll take your challenge!$"

gText_ByronWon::
	.string "Gwahahaha!\nHow were my sturdy Pokémon?!$"

gText_ByronDefeat::
	.string "Hmm!\nMy sturdy Pokémon--defeated!$"

gText_CandiceIntro::
	.string "You're the opponent of Candice?\pSure thing!\nI was waiting for someone tough!\pBut I should tell you, I'm tough,\nbecause I know how to focus.$"

gText_CandiceWon::
	.string "I sensed your will to win,\nbut I don't lose!$"

gText_CandiceDefeat::
	.string "You're mighty!\nYou're worthy of lots of respect.$"

gText_VolknerIntro::
	.string "The next opponent is you…\pI hope you're the Trainer who'll make\nme remember how fun it is to battle!$"

gText_VolknerWon::
	.string "It was not shocking at all…\nThat is not what I wanted!$"

gText_VolknerDefeat::
	.string "You've got me beat…\pYour desire and the noble way\nyour Pokémon battled for you…\pI even felt thrilled during\nour match.\pThat was a very good battle.$"

gText_CilanIntro::
	.string " So, um, if you're Ok with me, I'll, um,\nput everything I've got into being, er,\lyou know, your opponent.$"

gText_CilanWon::
	.string "Huh?\nDid I win?$"

gText_CilanDefeat::
	.string "Huh?\nIs it over?$"

gText_ChiliIntro::
	.string "Yeeeeooow!\pTime to play with FIRE!!\nI'm the strongest of the brothers!$"

gText_ChiliWon::
	.string "I'm on fire!\nPlay with me, and you'll get burned!$"

gText_ChiliDefeat::
	.string "You got me.\pI am…burned…out…$"

gText_CressIntro::
	.string "What incredible luck for you--you get to\nbattle the best among the three of us.$"

gText_CressWon::
	.string "This is the appropriate\nresult when I'm your opponent.$"

gText_CressDefeat::
	.string "Lose? Me?\nI don't believe this.$"

gText_LenoraIntro::
	.string "Well then, Trainer, I'm going to research\nhow you battle with the Pokémon\lyou've so lovingly raised!$"

gText_LenoraWon::
	.string "What's wrong? Could it be you misread\nwhat moves I was going to use?$"

gText_LenoraDefeat::
	.string "You're impressive!\nAnd quite charming, aren't you?!$"

gText_BurghIntro::
	.string "If the battle brings out the beauty in\nBug-type Pokémon, it will be a scene that\lmakes my heart flutter, win or lose.\pMy bug Pokémon are abuzz\nwith anticipation.\pLet's get straight to it!$"

gText_BurghWon::
	.string "Wow…\nIt's beautiful somehow, isn't it…$"

gText_BurghDefeat::
	.string "Is it over?\nHas my muse abandoned me?$"

gText_ElesaIntro::
	.string "I am me, and Pokémon are Pokémon!\pI feel that strongly when I\nbattle with Pokémon moves,\land that's why I do it.\pNow, my beloved Pokémon are\ngoing to make your head spin!$"

gText_ElesaWon::
	.string "That was unsatisfying somehow…\nWill you give it your all next time?$"

gText_ElesaDefeat::
	.string "I meant to make your head spin,\nbut you shocked me instead.$"

gText_ClayIntro::
	.string "How much stronger ya get comes\nfrom how much you want to win!\pAlways be loyal to that desire,\nya hear?$"

gText_ClayWon::
	.string "It's simple, hear!\nI wanted to win more than ya did!$"

gText_ClayDefeat::
	.string "Well, I've had enough… And just so you\nknow, I didn't go easy on you.$"

gText_SkylaIntro::
	.string "What I like is having fun!\pI love doing things like flying\nin the sky with Pokémon\land bringing out their best!\pSo, how about you and I\nhave some fun?$"

gText_SkylaWon::
	.string "Win or lose, you always gain\nsomething from a battle, right?$"

gText_SkylaDefeat::
	.string "Being your opponent in battle is a new\nsource of strength to me. Thank you!$"

gText_BrycenIntro::
	.string "You appear ready to face a battle.\pBring it!$"

gText_BrycenWon::
	.string "Extreme conditions really test you\nand train you!$"

gText_BrycenDefeat::
	.string "The wonderful combination\nof you and your Pokémon!\lWhat a beautiful friendship!$"

gText_DraydenIntro::
	.string "Thinking about aging is thinking\nabout the time you have left.\pNow, since there are\nfewer things I can do,\pwhat I want to find is a young Trainer\nwho can show me a bright future.$"

gText_DraydenWon::
	.string "Harrumph! I know your ability is greater\nthan that!$"

gText_DraydenDefeat::
	.string "This intense feeling that floods\nme after a defeat…\lI don't know how to describe it.$"

gText_CherenIntro::
	.string "Do you want to show how strong you\nare by winning, or do you want to\llearn what battling really means?\pPokémon battles have no meaning if\nyou don't think about why you battle.\pOr better said, it makes battling\ntogether with Pokémon meaningless.$"

gText_CherenWon::
	.string "Even when you lose, your Pokémon\nare still brimming with fighting spirit.$"

gText_CherenDefeat::
	.string "Thank you!\pI feel like I saw a little of\nthe way toward my ideals.$"

gText_RoxieIntro::
	.string "Fight with this Pokémon this way…\nUse this item that way…\lAre you letting others decide that\lfor you?\pWell, whatever, but what's important\nis figuring out what you want to do!\pGet ready! 'Cause I'm going to knock\nthe common sense outta you and drag\lyou into a brand new world!$"

gText_RoxieWon::
	.string "Hey, c'mon! Get serious!\nYou gotta put more out there!$"

gText_RoxieDefeat::
	.string "Wild!\pYour reason's already\nmore toxic than mine!$"

gText_MarlonIntro::
	.string "I'm strong like the ocean's wide.\nYou're gonna get swept away, fo' sho'.\pEh, that's enough talk! I'll prove it!\nLet's get started, 'K?$"

gText_MarlonWon::
	.string "You're tough, but it's not\nenough to sway the sea, 'K!$"

gText_MarlonDefeat::
	.string "You're strong as a gnarly wave\nand as nice as a glassy sea.$"

gText_RedIntro::
	.string "…$"

gText_RedWon::
	.string "…?$"

gText_RedDefeat::
	.string "…!!$"

gText_BlueIntro::
	.string "But, I'm a Trainer.\pIf I see a strong opponent, it makes me\nwant to battle.$"

gText_BlueWon::
	.string "This is what I, Kanto's top-level\nTrainer, can really do!$"

gText_BlueDefeat::
	.string "How the heck did I lose to you?$"

gText_LanceIntro::
	.string "You are brimming with love\nand trust toward Pokémon.\pI think we will be able to\nhave a fantastic battle!$"

gText_LanceWon::
	.string "I never give up, no matter what.\nYou must be the same?$"

gText_LanceDefeat::
	.string "…It's over.$"

gText_StevenIntro::
	.string "My name is Steven.\pI'm interested in rare Stones, so\nI travel here and there.$"

gText_StevenWon::
	.string "When it comes down to it,\nI'm still the strongest!$"

gText_StevenDefeat::
	.string "You are a truly noble Pokémon Trainer!$"

gText_CynthiaIntro::
	.string "One look at you tells\nme many things about you.\pTogether, you and your Pokémon\novercame all the challenges you\lfaced, however difficult.\pI, Cynthia, accept your challenge!\pThere won't be any letup from me!$"

gText_CynthiaWon::
	.string "What's necessary to become\nstronger?\p think it's important to never lose\nyour love of Pokémon.$"

gText_CynthiaDefeat::
	.string "Aww!\pNo matter how fun the battle is,\nit will always end sometime…$"

gText_AlderIntro::
	.string "I've really been looking forward\nto deciding who's the strongest\lPokémon Trainer in this tournament!\pKiai!$"

gText_AlderWon::
	.string "That was an extraordinary effort\nfrom both you and your Pokémon!$"

gText_AlderDefeat::
	.string "Well done!\nYou certainly are an unmatched talent!$"

gText_IrisIntro::
	.string "I really look forward to having\nserious battles with strong Trainers!\pThe Trainers who make it here\nare Trainers who desire victory\lwith every fiber of their being!$"

gText_IrisWon::
	.string "Did you not seriously try to\nwin?$"

gText_IrisDefeat::
	.string "Aghhhh…\nI did my best, but we lost…$"

