Route102_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route103_EventScript_ItemGuardSpec::
	finditem ITEM_GUARD_SPEC
	end

Route103_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route104_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route104_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route104_EventScript_ItemXAccuracy::
	finditem ITEM_GRIP_CLAW
	end

Route104_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route105_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route106_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route108_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route109_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route109_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route110_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route110_EventScript_ItemDireHit::
	finditem ITEM_DIRE_HIT
	end

Route110_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route111_EventScript_ItemTM37::
	finditem ITEM_TM37
	end

Route111_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

Route111_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route111_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route112_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route113_EventScript_ItemMaxEther::
	finditem ITEM_TM32
	end

Route113_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route113_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route114_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route114_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route114_EventScript_ItemEnergyPowder::
	finditem ITEM_ENERGY_POWDER
	end

Route115_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

Route115_EventScript_ItemTM01::
	finditem ITEM_TM01
	end

Route115_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route115_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route115_EventScript_ItemHealPowder::
	finditem ITEM_HEAL_POWDER
	end

Route115_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route116_EventScript_ItemXSpecial::
	finditem ITEM_X_SP_ATK
	end

Route116_EventScript_ItemEther::
	finditem ITEM_PROTEIN
	end

Route116_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

Route116_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route116_EventScript_ItemPotion::
	finditem ITEM_LAX_MINT
	end

RuggedRoad_EventScript_ItemAirBalloon::
	finditem ITEM_AIR_BALLOON
	end

Route117_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route117_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route118_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route119_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route119_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route119_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

Route119_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route119_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemHyperPotion2::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemElixir2::
	finditem ITEM_ELIXIR
	end

Route120_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route120_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

Route120_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route120_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

Route120_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route121_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route123_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

Route123_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route123_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route123_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route123_EventScript_ItemRevivalHerb::
	finditem ITEM_REVIVAL_HERB
	end

Route124_EventScript_ItemRedShard::
	finditem ITEM_RED_SHARD
	end

Route124_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

Route124_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

Route125_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route126_EventScript_ItemGreenShard::
	finditem ITEM_GREEN_SHARD
	end

Route127_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route127_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route127_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route133_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route133_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route133_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

Route134_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route134_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

PetalburgCity_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

PetalburgCity_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

MauvilleCity_EventScript_ItemXSpeed::
	finditem ITEM_X_SPEED
	end

RustboroCity_EventScript_ItemXDefend::
	finditem ITEM_X_DEFENSE
	end

LilycoveCity_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

MossdeepCity_EventScript_ItemNetBall::
	finditem ITEM_NET_BALL
	end

PetalburgWoods_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

PetalburgWoods_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

PetalburgWoods_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

PetalburgWoods_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

RusturfTunnel_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

RusturfTunnel_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

GraniteCave_1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

GraniteCave_B1F_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

GraniteCave_B2F_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

GraniteCave_B2F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

JaggedPass_EventScript_ItemBurnHeal::
	finditem ITEM_BURN_HEAL
	end

FieryPath_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

FieryPath_EventScript_ItemTM06::
	finditem ITEM_TM06
	end

MeteorFalls_1F_1R_EventScript_ItemTM23::
	finditem ITEM_TM23
	end

MeteorFalls_1F_1R_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

DewfordDojo_EventScript_ItemTM66::
	finditem ITEM_TM66
	end

MeteorFalls_1F_1R_EventScript_ItemPPUP::
	finditem ITEM_PP_UP
	end

MeteorFalls_B1F_2R_EventScript_ItemTM02::
	finditem ITEM_TM02
	end

NewMauville_Inside_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

NewMauville_Inside_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

NewMauville_Inside_EventScript_ItemElectricMemory::
	finditem ITEM_ELECTRIC_MEMORY
	end

NewMauville_Inside_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall::
	finditem ITEM_DIVE_BALL
	end

AbandonedShip_Room_B1F_EventScript_ItemTM13::
	finditem ITEM_TM13
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
	finditem ITEM_STORAGE_KEY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall::
	finditem ITEM_LUXURY_BALL
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
	finditem ITEM_SCANNER
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
	finditem ITEM_WATER_STONE
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18::
	finditem ITEM_TM18
	end

ScorchedSlab_EventScript_ItemTM11::
	finditem ITEM_TM11
	end

SafariZone_Northwest_EventScript_ItemTM22::
	finditem ITEM_TM22
	end

SafariZone_North_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

SafariZone_Southwest_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

SafariZone_Northeast_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

SafariZone_Southeast_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

MtPyre_2F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

MtPyre_3F_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

MtPyre_4F_EventScript_ItemSeaIncense::
	finditem ITEM_SEA_INCENSE
	end

MtPyre_5F_EventScript_ItemLaxIncense::
	finditem ITEM_LAX_INCENSE
	end

MtPyre_6F_EventScript_ItemTM30::
	finditem ITEM_TM30
	end

MtPyre_Exterior_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

MtPyre_Exterior_EventScript_ItemTM61::
	finditem ITEM_TM61
	end

AquaHideout_B1F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL
	end

AquaHideout_B1F_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

AquaHideout_B1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

AquaHideout_B2F_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

AquaHideout_B2F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route119_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

Route119_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
	finditem ITEM_ICE_HEAL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTM07::
	finditem ITEM_TM07
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

RuggedCave3_EventScript_ItemIcyRock::
	finditem ITEM_ICY_ROCK
	end

SeafloorCavern_Room9_EventScript_ItemTM26::
	finditem ITEM_TM26
	end

LakeValor_EventScript_ItemPidgeotite::
	finditem ITEM_PIDGEOTITE
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
	finditem ITEM_ORANGE_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
	finditem ITEM_WAVE_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
	finditem ITEM_SHADOW_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
	finditem ITEM_WOOD_MAIL
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
	finditem ITEM_MECH_MAIL
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
	finditem ITEM_GLITTER_MAIL
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
	finditem ITEM_TROPIC_MAIL
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
	finditem ITEM_BEAD_MAIL
	end

VictoryRoad_1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

VictoryRoad_1F_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

VictoryRoad_B1F_EventScript_ItemTM29::
	finditem ITEM_TM29
	end

VictoryRoad_B1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

VictoryRoad_B2F_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

ArtisanCave_B1F_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

ArtisanCave_1F_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

MagmaHideout_1F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

MagmaHideout_3F_1R_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax::
	finditem ITEM_PP_MAX
	end

MagmaHideout_4F_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end
Common_EventScript_FindItem::
	callnative GetItemBallIdAndAmountFromTemplate
	finditem VAR_RESULT VAR_0x8009
	end

SafariZone_South_EventScript_ItemAbsolite:: @ 82912F0
	finditem ITEM_ABSOLITE
	end

Slateport_EventScript_ItemAlakazite:: @ 82912F0
	finditem ITEM_ALAKAZITE
	end

MtPyre_EventScript_ItemBanettite:: @ 82912F0
	finditem ITEM_BANETTITE
	end

AbandonedShip_EventScript_ItemBeedrillite:: @ 82912F0
	finditem ITEM_BEEDRILLITE
	end

RuggedCave3_EventScript_ItemGlalitite:: @ 82912F0
	finditem ITEM_GLALITITE
	end

RuggedRoad_EventScript_ItemHeracronite:: @ 82912F0
	finditem ITEM_HERACRONITE
	end

DewfordDojo_Indoors_EventScript_ItemSleepTalk::
	finditem ITEM_TM88
	end

NewMauville_Inside3F_ItemManectite:: @ 82912F0
	finditem ITEM_MANECTITE
	end

Route117_EventScript_ItemMawilite:: @ 82912F0
	finditem ITEM_MAWILITE
	end

MtPyre_EventScript_ItemMedichamite:: @ 82912F0
	finditem ITEM_MEDICHAMITE
	end

Route124_EventScript_ItemPinsirite:: @ 82912F0
	finditem ITEM_PINSIRITE
	end

Sootopolis_EventScript_ItemSablenite:: @ 82912F0
	finditem ITEM_SABLENITE
	end

Route111_DesertPass_EventScript_ItemSteelixite:: @ 82912F0
	finditem ITEM_STEELIXITE
	end

MtChimneyDepths_EventScript_ItemFlamePlate::
	finditem ITEM_FLAME_PLATE
	end

VajraDesertTunnels_EventScript_ItemEarthPlate::
	finditem ITEM_EARTH_PLATE
	end

MtChimneyDepths_EventScript_ItemFlameOrb::
	finditem ITEM_FLAME_ORB
	end

Faraway_Island_Cave_EventScript_ItemSmoothRock:: @ 82912F0
	finditem ITEM_SMOOTH_ROCK
	end

NamelessDungeon_EventScript_ItemNugget:: @ 82912F0
	finditem ITEM_NUGGET
	end

NamelessDungeon_EventScript_ItemFullRestore:: @ 82912F0
	finditem ITEM_FULL_RESTORE
	end

NamelessDungeon_EventScript_ItemDuskStone:: @ 82912F0
	finditem ITEM_DUSK_STONE
	end

NamelessDungeon_EventScript_ItemAssaultVest:: @ 82912F0
	finditem ITEM_ASSAULT_VEST
	end

NamelessDungeon_EventScript_ItemElectirizer:: @ 82912F0
	finditem ITEM_ELECTIRIZER
	end

NamelessDungeon_EventScript_ItemBlackSludge:: @ 82912F0
	finditem ITEM_BLACK_SLUDGE
	end

NamelessDungeon_EventScript_ItemPPMax:: @ 82912F0
	finditem ITEM_PP_MAX
	end

NamelessDungeon_EventScript_ItemMaxRevive:: @ 82912F0
	finditem ITEM_MAX_REVIVE
	end

NamelessDungeon_EventScript_ItemMaxElixir:: @ 82912F0
	finditem ITEM_MAX_ELIXIR
	end

Route123_EventScript_ItemAbomasite:: @ 82912F0
	finditem ITEM_ABOMASITE
	end

MeteorFalls_EventScript_ItemAerodactylite:: @ 82912F0
	finditem ITEM_AERODACTYLITE
	end

NewMauville_EventScript_ItemAmpharosite:: @ 82912F0
	finditem ITEM_AMPHAROSITE
	end

FieryPath_EventScript_ItemCharizarditeX:: @ 82912F0
	finditem ITEM_CHARIZARDITE_X
	end

ScorchedSlab_EventScript_ItemCharizarditeY:: @ 82912F0
	finditem ITEM_CHARIZARDITE_Y
	end

Lavaridge_EventScript_ItemHoundoominite:: @ 82912F0
	finditem ITEM_HOUNDOOMINITE
	end

Pacifidlog_EventScript_ItemKangaskhanite:: @ 82912F0
	finditem ITEM_KANGASKHANITE
	end

Littleroot_EventScript_ItemMewtwoniteX:: @ 82912F0
	finditem ITEM_MEWTWONITE_X
	end

EverGrande_EventScript_ItemMewtwoniteY:: @ 82912F0
	finditem ITEM_MEWTWONITE_Y
	end

JaggedPass_EventScript_ItemTyranitarite:: @ 82912F0
	finditem ITEM_TYRANITARITE
	end

PetalburgWoods_EventScript_ItemScizorite:: @ 82912F0
	finditem ITEM_SCIZORITE
	end

Route119_EventScript_ItemVenusaurite:: @ 82912F0
	finditem ITEM_VENUSAURITE
	end

BatlleFrontier_EventScript_ItemGengarite:: @ 82912F0
	finditem ITEM_GENGARITE
	end

SSTidal_EventScript_ItemBlastoisinite:: @ 82912F0
	finditem ITEM_BLASTOISINITE
	end



Route132_EventScript_ItemTM34:: @ 82912F0
	finditem ITEM_TM34
	end

VictoryRoad_EventScript_ItemTM35:: @ 82912F0
	finditem ITEM_TM35
	end

JaggedPass_EventScript_ItemTM43:: @ 82912F0
	finditem ITEM_TM43
	end

MtChimney_EventScript_ItemTM59:: @ 82912F0
	finditem ITEM_TM59
	end

MtPyre_EventScript_ItemTM61:: @ 82912F0
	finditem ITEM_TM61
	end

Route119_EventScript_ItemTM62:: @ 82912F0
	finditem ITEM_TM62
	end

GraniteCave_EventScript_ItemTM65:: @ 82912F0
	finditem ITEM_TM65
	end

Route134_EventScript_ItemTM80:: @ 829109A
	finditem ITEM_TM80
	end

SafariZone_North_EventScript_ItemTM53:: @ 82912BC
	finditem ITEM_TM53
	end

SafariZone_Southeast_EventScript_ItemTM93:: @ 82912F0
	finditem ITEM_TM93
	end

AquaHideout_B2F_EventScript_ItemTM97:: @ 829138C
	finditem ITEM_TM97
	end

RuggedCave3_EventScript_ItemTM79:: @ 82913CD
	finditem ITEM_TM79
	end

RuggedRoad_EventScript_ItemTM83:: @ 82913CD
	finditem ITEM_TM83
	end

SeafloorCavern_Room7_EventScript_ItemTM55:: @ 8291401
	finditem ITEM_TM55
	end

SkyPillar_4F_EventScript_ItemTM64:: @ 82913E7
	finditem ITEM_TM64
	end

VictoryRoad_B2F_EventScript_ItemTM81:: @ 82914B7
	finditem ITEM_TM81
	end

Route123_EventScript_ItemGyaradosite:: @ 82912F0
	finditem ITEM_GYARADOSITE
	end

JaggedPass_EventScript_ItemTM69:: @ 82912F0
	finditem ITEM_TM69
	end

FortreeCity_EventScript_ItemTM86:: @ 82912F0
	finditem ITEM_TM86
	end

Slateport_Market_EventScript_ItemWaterMemory::
	finditem ITEM_WATER_MEMORY
	end

Slateport_Underwater_EventScript_ItemWateriumZ::
	finditem ITEM_WATERIUM_Z
	end

MeteorFalls_B1F_2R_EventScript_ItemSalamencite:: @ 82911DF
	finditem ITEM_SALAMENCITE
	end

SouthernIsland_Interior_EventScript_ItemLatiasite:: @ 82912F0
	finditem ITEM_LATIASITE
	end

SouthernIsland_Interior_EventScript_ItemLatiosite:: @ 82912F0
	finditem ITEM_LATIOSITE
	end

FortreeCity_EventScript_Garchompite:: @ 82912F0
	finditem ITEM_GARCHOMPITE
	end

MauvilleCity_EventScript_Lopunnite:: @ 82912F0
	finditem ITEM_LOPUNNITE
	end

BattleFrontier_EventScript_Audinite:: @ 82912F0
	finditem ITEM_AUDINITE
	end
