#ifndef GUARD_BATTLE_DOME_H
#define GUARD_BATTLE_DOME_H

extern u32 gPlayerPartyLostHP;

static const u16 gFrontierKantoLeaders[] =
{
    TRAINER_FRONTIER_BROCK,
    TRAINER_FRONTIER_MISTY,
    TRAINER_FRONTIER_SURGE,
    TRAINER_FRONTIER_ERIKA,
    TRAINER_FRONTIER_JANINE,
    TRAINER_FRONTIER_SABRINA,
    TRAINER_FRONTIER_BLAINE,
    TRAINER_FRONTIER_GIOVANNI,
};

static const u16 gFrontierJohtoLeaders[] =
{
    TRAINER_FRONTIER_FALKNER,
    TRAINER_FRONTIER_BUGSY,
    TRAINER_FRONTIER_WHITNEY,
    TRAINER_FRONTIER_MORTY,
    TRAINER_FRONTIER_CHUCK,
    TRAINER_FRONTIER_JASMINE,
    TRAINER_FRONTIER_PRYCE,
    TRAINER_FRONTIER_CLAIR,
};

static const u16 gFrontierHoennLeaders[] =
{
    TRAINER_FRONTIER_ROXANNE,
    TRAINER_FRONTIER_BRAWLY,
    TRAINER_FRONTIER_WATTSON,
    TRAINER_FRONTIER_FLANNERY,
    TRAINER_FRONTIER_NORMAN,
    TRAINER_FRONTIER_WINONA,
    TRAINER_FRONTIER_TATE,
    TRAINER_FRONTIER_LIZA,
    TRAINER_FRONTIER_WALLACE,
};

static const u16 gFrontierSinnohLeaders[] =
{
    TRAINER_FRONTIER_ROARK,
    TRAINER_FRONTIER_GARDENIA,
    TRAINER_FRONTIER_MAYLENE,
    TRAINER_FRONTIER_WAKE,
    TRAINER_FRONTIER_FANTINA,
    TRAINER_FRONTIER_BYRON,
    TRAINER_FRONTIER_CANDICE,
    TRAINER_FRONTIER_VOLKNER,
};

static const u16 gFrontierUnovaLeaders[] =
{
    TRAINER_FRONTIER_CILAN,
    TRAINER_FRONTIER_CHILI,
    TRAINER_FRONTIER_CRESS,
    TRAINER_FRONTIER_LENORA,
    TRAINER_FRONTIER_BURGH,
    TRAINER_FRONTIER_ELESA,
    TRAINER_FRONTIER_CLAY,
    TRAINER_FRONTIER_SKYLA,
    TRAINER_FRONTIER_BRYCEN,
    TRAINER_FRONTIER_DRAYDEN,
    TRAINER_FRONTIER_CHEREN,
    TRAINER_FRONTIER_ROXIE,
    TRAINER_FRONTIER_MARLON,
};

static const u16 gFrontierWorldLeaders[] =
{
    TRAINER_FRONTIER_BROCK,
    TRAINER_FRONTIER_MISTY,
    TRAINER_FRONTIER_SURGE,
    TRAINER_FRONTIER_ERIKA,
    TRAINER_FRONTIER_JANINE,
    TRAINER_FRONTIER_SABRINA,
    TRAINER_FRONTIER_BLAINE,
    TRAINER_FRONTIER_GIOVANNI,
    TRAINER_FRONTIER_FALKNER,
    TRAINER_FRONTIER_BUGSY,
    TRAINER_FRONTIER_WHITNEY,
    TRAINER_FRONTIER_MORTY,
    TRAINER_FRONTIER_CHUCK,
    TRAINER_FRONTIER_JASMINE,
    TRAINER_FRONTIER_PRYCE,
    TRAINER_FRONTIER_CLAIR,
    TRAINER_FRONTIER_ROXANNE,
    TRAINER_FRONTIER_BRAWLY,
    TRAINER_FRONTIER_WATTSON,
    TRAINER_FRONTIER_FLANNERY,
    TRAINER_FRONTIER_NORMAN,
    TRAINER_FRONTIER_WINONA,
    TRAINER_FRONTIER_TATE,
    TRAINER_FRONTIER_LIZA,
    TRAINER_FRONTIER_WALLACE,
    TRAINER_FRONTIER_ROARK,
    TRAINER_FRONTIER_GARDENIA,
    TRAINER_FRONTIER_MAYLENE,
    TRAINER_FRONTIER_WAKE,
    TRAINER_FRONTIER_FANTINA,
    TRAINER_FRONTIER_BYRON,
    TRAINER_FRONTIER_CANDICE,
    TRAINER_FRONTIER_VOLKNER,
    TRAINER_FRONTIER_CILAN,
    TRAINER_FRONTIER_CHILI,
    TRAINER_FRONTIER_CRESS,
    TRAINER_FRONTIER_LENORA,
    TRAINER_FRONTIER_BURGH,
    TRAINER_FRONTIER_ELESA,
    TRAINER_FRONTIER_CLAY,
    TRAINER_FRONTIER_SKYLA,
    TRAINER_FRONTIER_BRYCEN,
    TRAINER_FRONTIER_DRAYDEN,
    TRAINER_FRONTIER_CHEREN,
    TRAINER_FRONTIER_ROXIE,
    TRAINER_FRONTIER_MARLON,
};

int GetDomeTrainerSelectedMons(u16 tournamentTrainerId);
int TrainerIdToDomeTournamentId(u16 trainerId);

#endif // GUARD_BATTLE_DOME_H
